config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  
  #User routes
  root "users#index"
  get "/users" => "users#index", as: "users"
  get "/signup" => "users#new", as: "new_user"
  post "/users" => "users#create"
  get "/users/:id" => "users#show", as: "user"

  #Session routes
  get "/login" => "sessions#new"
  post "/sessions" => "sessions#create"
  get "/logout" => "sessions#destroy"

  #Library routes
  get "/libraries" => "libraries#index"
  get "/libraries/new" => "libraries#new", as: "new_library"
  post "/libraries" => "libraries#create"

  #Library User routes
  get "/users/:user_id/libraries" => "library_users#index", as: "user_libraries"
  post "/libraries/:library_id/users" => "library_users#create", as: "library_users"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/library.rb
class Library < ApplicationRecord
    has_many :library_users
    has_many :users, through: :library_users
end

app/models/library_user.rb
class LibraryUser < ApplicationRecord
  belongs_to :user
  belongs_to :library
end

app/models/user.rb
class User < ApplicationRecord
    has_secure_password
    has_many :library_users
    has_many :libraries, through: :library_users
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
# Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/libraries_controller.rb
class LibrariesController < ApplicationController
    def index
        @libraries = Library.all
        current_user
    end

    def new
        render :new
    end

    def create
        library = Library.create(
            name: params[:name],
            floor_count: params[:floor_count],
            book_count: params[:book_count]
        )
        redirect_to libraries_path
    end
end

app/controllers/library_users_controller.rb
class LibraryUsersController < ApplicationController
    def index
        @user = User.find(params[:user_id])
        @libraries = @user.libraries
        current_user
    end  
    
    def create
        @user = current_user
        @library = Library.find(params[:library_id])
        @user.libraries.push(@library)

        redirect_to user_libraries_path(@user)
    end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
    def new
    end

    def create
        user = User.find_by(email: params[:email])
        if user && user.authenticate(params[:password])
            login(user)
            redirect_to user_path(user)
        else
            redirect_to "/login"
        end
    end

    def destroy
        logout
        redirect_to users_path
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    def index
        @users = User.all
    end

    def new
        render :new
    end

    def create
        user = User.create(
            first_name: params[:first_name],
            last_name: params[:last_name],
            email: params[:email],
            password: params[:password]
            )
        redirect_to users_path
    end

    def show
        @user = User.find(params[:id])
    end


end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/libraries_helper.rb
module LibrariesHelper
end

app/helpers/library_users_helper.rb
module LibraryUsersHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
    def login(user)
        session[:user_id] = user.id
        @current_user = user
    end

    def current_user
        @current_user ||= User.find(session[:user_id])
    end

    def logout
        @current_user = session[:user_id] = nil
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LibApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/libraries/index.html.erb
<h1>Library List</h1>
<% @libraries.each do |library| %>
  <div>
    <h3><%= library.name %></h3>
    <% if @current_user %>
      <%= button_to "Join", library_users_path(library)%>
    <% end %>
  </div>
  <br>
<% end %>

app/views/libraries/new.html.erb
<%=  form_tag "/libraries", method: :post do %>
  <div>
    <%= text_field_tag :name, nil, placeholder: "Name" %>
  </div>
  <div>
    <%= number_field_tag :floor_count, nil, placeholder: "Floor Count" %>
  </div>
  <div>
    <%= number_field_tag :book_count,  nil, placeholder: "Book Count" %>
  </div>
  <%= submit_tag "Add Library" %>
<% end %>

app/views/library_users/index.html.erb
<div><%= @user.first_name %> is a member of the following libraries</div>

<ul>
  <% @libraries.each do |lib| %>
    <li><%= lib.name %></li>
  <% end %>
</ul>

app/views/users/index.html.erb
<h1>Welcome to Users Index</h1>
<div>
    There are currently <%= @users.length %> users signed up.
    <%= link_to "Sign Up", controller: "users", action: "new"%>

</div>

app/views/users/new.html.erb
<%= form_tag "/users", method: :post do %>
  <div>
     <%= text_field_tag :first_name, nil, placeholder: "First Name" %>
  </div>
  <div>
    <%= text_field_tag :last_name, nil, placeholder: "Last Name" %>
  </div>
  <div>
    <%= text_field_tag :email, nil, placeholder: "Email" %>
  </div>
  <div>
    <%= password_field_tag :password, nil, placeholder: "Password" %>
  </div>
  <%= submit_tag "Sign Up" %>
<% end %>

app/views/users/show.html.erb
<div>
  Welcome, <%= @user.first_name %>
  <%= link_to "Sign Out", controller: "sessions", action: "destroy"%>
</div>